---
title: "あぁぁ... 現在のリポジトリを別のリモートに保存したい..."
author: 
   - name: "Ryo Nakagami"
     url: https://github.com/RyoNakagami
date: "2024-07-26"
date-modified: "2025-06-14"
categories: [git clone]
---

## 問題

GitHubでホストされているリポジトリ`LinearModels`で，同僚とリモートおよび/またはローカルで作業をしているとします．
現在のリポジトリで開発が進行中ですが，上司から現時点での履歴を保持したまま，
Gitlabリポジトリ`https://gitlab.econometrics.com/EXAMPLE-USER/NEW-REPOSITORY.git`にミラーリングするよう依頼されました．

## 解決策: `git clone --bare`

<strong > &#9654;&nbsp; 手順</strong>

1. リポジトリのベアクローンを作成
2. 新しいリポジトリにミラーpush
3. 一時的な古いローカルリポジトリを削除

<strong > &#9654;&nbsp; コマンド</strong>

```zsh
# ステップ1
% git clone --bare https://github.com/EXAMPLE-USER/LinearModels.git

# ステップ2
% cd LinearModels.git
% git push --mirror https://gitlab.econometrics.com/EXAMPLE-USER/NEW-REPOSITORY.git

# ステップ3
% cd ..
% rm -rf LinearModels.git
```

<div class="blog-custom-border">
<strong >REAMRKS</strong> <br>

- 通常の`git clone`はスナップショットと履歴の両方をローカルマシンにダウンロードしますが，`git clone --bare`は履歴のみをコピーするため，新しいリモートリポジトリへの転送が迅速に行えます．
- また，ベアリポジトリから通常のリポジトリを作成することもできます．ほとんどの場合，push先の新しいリポジトリは通常のリポジトリである必要があります．
- ミラーリングプロセスはローカルと新しいリモートリポジトリ間の通信を通じて行われるため，古いリモートリポジトリは新しいリポジトリの通知や更新を受け取りません．

</div>

### なぜ通常の`git clone` と `git push --mirror`を使わないのか？

`git clone <origin-url>`を実行すると，すべてのタグがコピーされ，
リモートブランチ`origin/master`を追跡するローカルブランチmaster（`HEAD`）と，リモート
ブランチ`origin/test1`，`origin/test2`，`origin/test3`が作成されます．

通常のクローンリポジトリに対して`git push --mirror`を実行すると，mirrorは全てを意味するため，
リモートブランチ`origin/test1`，`origin/test2`，`origin/test3`もpushされます．
その結果，`origin/origin/test1`という名前のブランチが作成されてしまいます．

📘 References
----------
- [GitHub Docs > Duplicating a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository)
