project:
  type: website

website:
  title: "OhGoshGit!?!"
  site-url: https://ohgoshgit.github.io/
  google-analytics: 
    tracking-id: "G-2W179PEWKM"
  favicon: ./img/favicon-32x32.png
  repo-url: https://github.com/OhGoshGit/OhGoshGit.github.io
  issue-url: https://github.com/OhGoshGit/OhGoshGit.github.io/issues
  repo-actions: [issue]
  navbar:
    left: 
      - text: "Dangit, Git!?!"
        href: https://dangitgit.com/
      - about.qmd
    right:
      - href: ./language/jp/
        text: 日本語
      - href: ./
        text: English
      - icon: github
        href: https://github.com/OhGoshGit/OhGoshGit.github.io
      - icon: rss
        href: index.xml
  page-footer:
    center:
      - text: © Copyright RyoNak
      - text: "License"
        href: LICENSE
  comments:
    utterances:
         repo: OhGoshGit/OhGoshGit.github.io
         label: discussion
         issue-term: title

format:
  html:
    include-in-header: 
      - _include/setup_googletagmanager.html
      - _include/custom_webfont.html
    include-in-body: _include/setup_googletagmanager_body.html
    include-after-body: _include/custom_section.html
    theme: 
      light: 
        - cosmo
        - _include/custom.scss
        - _include/light.scss
      dark: 
        - darkly
        - _include/custom.scss
        - _include/dark.scss
    code-copy: true
    code-fold: true
    code-overflow: wrap
    date-format: "iso"
    css: styles.css
    fontsize: 21px
    mainfont: "Noto Sans JP"
    monofont: monospace
    toc: true
    highlight: arrow
    page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 250px

tbl-cap-location: top