name: rss-to-twitter
on:
  schedule:
    # every 15 minutes
    - cron: "*/60 * * * *"
  workflow_dispatch:
jobs:
  twitter:
    # if github.event.build.error.message is not null, it means that the build failed. Skip it
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v2
        with:
          RSS_URL: "https://ohgoshgit.github.io/index.xml"
          TWEET_TEMPLATE: 'New Post: "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 1440 # post items that are published within 15 minutes
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}